#!/bin/bash


export ENV_NAME=default
export ENV_DIR="./envs/default"

export ROCKETCHAT_FQDN=
export ROCKETCHAT_SMTP_ENABLED=
export ROCKETCHAT_SMTP_USERNAME=
export ROCKETCHAT_SMTP_PASSWORD=
export ROCKETCHAT_SMTP_HOST=
export ROCKETCHAT_SMTP_PORT=
export ROCKETCHAT_MONGO_ROOT_PASSWORD=
export ROCKETCHAT_MONGO_USERNAME=
export ROCKETCHAT_MONGO_PASSWORD=
export ROCKETCHAT_MONGO_KEY=